{% set name = "cirun" %}
{% set version = "0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cirun-{{ version }}.tar.gz
  sha256: bb4401968fe1fad050ffc5d361c436debe483a6e3ddcd7f6e8066dcd3e750ec1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - cirun = cirun.main:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - hatch
    - hatchling
    - requests
    - rich
    - typer

test:
  imports:
    - cirun
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/cirun/
  summary: Cirun Python Client
  dev_url: https://github.com/aktechlabs/cirun-py
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aktech
    - aktechlabs-bot
    - cirun-bot
